name = "trabalho_1"
version = "0.1.0"
license = "license"
author = "igor-inoue"
maintainer = "igor.inoue@ufv.br"
copyright = "Copyright 2024, igor-inoue"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
[dependencies]
   tictoc-fortran.git = "https://github.com/wcota/tictoc-fortran"

